name: Update ProxyPool

on:
  schedule:
    - cron: '15 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build and Run
        run: |
          go mod download
          go build -o proxypool ./...
          ./proxypool

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add source/ -f
          git diff --staged --quiet || git commit -m "Update proxies $(date '+%Y-%m-%d %H:%M:%S')"
          git push
